solve emails and meetups
js-tasks-ru/vue-20240627_evgeniy-petrov3 pull request #6
Opened 2024-09-02 16:13 UTC by EvgeniiPetrov187

2024-09-02 16:14 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-09-02 16:25 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-09-05 21:00 UTC, ShGKme requested changes
Требуются исправления в последне1й задаче по комментариям

2024-09-05 21:00 UTC, ShGKme commented on 02-basics-2/50-selected-meetup/SelectedMeetupApp.js
> +              value="{{ itemId }}"
`{{ ... }}` - это текстовая интерполяция. Ей можно только определять текстовое содержимое узлов, но не HTML в целом или значение атрибутов. Здесь должна быть привязка с `v-bind`: 
`:value="itemId"`

2024-09-05 21:00 UTC, ShGKme commented on 02-basics-2/50-selected-meetup/SelectedMeetupApp.js
> +              @change="setCount(itemId)"
Вместо отдельно проверки `checked` и обработки `change` лучше использовать `v-model`. Он заработает, если правильно указать `value`

2024-09-05 21:00 UTC, ShGKme commented on 02-basics-2/50-selected-meetup/SelectedMeetupApp.js
> +    }
Лучше не переусложнять с множеством таких простых функций. Если такою проверку в одно выражение оставить в шаблоне, будет проще понимать, какой результат шаблона.

2024-09-05 21:00 UTC, ShGKme commented on 02-basics-2/50-selected-meetup/SelectedMeetupApp.js
> +    }));
Такое объявление переменной - некорректное. `.then()` возвращает промис. В итоге изначально в переменной `meetUp` хранится `Promise`, а в шаблоне выводится `promise.title`. Это не приводит к проблеме, так как JS позволяет обращаться к несуществующим полям. Но оставляет неправильный объект в переменной на время получения данных.

2024-09-07 08:16 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-09-07 08:20 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-09-08 21:05 UTC, ShGKme approved these changes
Принято, но обратите внимание на комментарии.

2024-09-08 21:05 UTC, ShGKme commented on 02-basics-2/50-selected-meetup/SelectedMeetupApp.js
> +    };
Сейчас у переменной митап не очень определённый тип. Изначально это строка (пустая), а после получения данных - объект. Лучше начальным значением явно указывать `null` как отсутствие значения.

2024-09-08 21:05 UTC, ShGKme commented on 02-basics-2/50-selected-meetup/SelectedMeetupApp.js
> +          <h1 class="meetup-cover__title">{{ meetUp.title }}</h1>
Например, здесь при первом рендеринге идёт обращение к полю `title` у строки. Такого поля у строки быть не может, хотя JS позволяет так обращаться и просто выводится пустой заголовок.

2024-09-08 21:05 UTC, ShGKme commented on 02-basics-2/50-selected-meetup/SelectedMeetupApp.js
> +              :checked="itemId === current"
Привязка `checked` не нужна, если есть `v-model`, так как он является короткой записью для и `@change` и `:checked`.

2024-09-08 21:06 UTC, merged