solve components
js-tasks-ru/vue-20240627_evgeniy-petrov3 pull request #7
Opened 2024-09-29 06:53 UTC by EvgeniiPetrov187

Все задачи по компонентам

2024-09-29 06:53 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-01 23:34 UTC, ShGKme requested changes
Требуются небольшие исправления

2024-10-01 23:34 UTC, ShGKme commented on 03-components/10-MeetupView/MeetupView.js
>    },
Лучше максимально подробно описывать параметры компонента - тип и обязательность/значение по умолчанию.

2024-10-01 23:34 UTC, ShGKme commented on 03-components/30-removable-emails/EmailList.js
> +        @remove-email="$emit('removeEmail', index)"
Хотя компонент работает и без явного описания событий в `emits`, настоятельно рекомендуется всегда описыватьсобытия в `emits`:

- Так у компонента есть документация и типизация для разработчиков и различных инструментов
- В случае, если имя события совпадает с DOM событием, оно будет дублироваться

2024-10-01 23:34 UTC, ShGKme commented on 03-components/30-removable-emails/EmailList.js
>      },
В объекте описания пропсов нет такого свойства описания, как `index`. Если это новый пропс, то он должен быть в объекте `props`. Но он здесь не используется в любом случае.

2024-10-01 23:34 UTC, ShGKme commented on 03-components/30-removable-emails/EmailListItem.js
> +      index: Number,
Аналогично предыдущему комментарию

2024-10-01 23:34 UTC, ShGKme commented on 03-components/30-removable-emails/MarkedEmailsApp.js
> +      <EmailList :emails="markedEmails" @remove-email="(index) => removeEmailByIndex(index)"/>
`(index) => removeEmailByIndex(index)` - тоже что просто `removeEmailByIndex`. Функция будет вызвана с параметром события.

2024-10-03 15:20 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-03 16:32 UTC, ShGKme requested changes
В `03-components/30-removable-emails` осталась проблема с объявлением событий в опции `emits`

2024-10-03 17:11 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-03 17:24 UTC, ShGKme commented on 03-components/30-removable-emails/EmailList.js
> +  emits: ['removeEmail:index'],
Имя события - это только имя. То имя, которое мы передаём в функцию `emit`. Например, если вызывается `$emit('removeEmail', index)`, то событие называется `removeEmail` и в опции `emits` должно быть именно это имя. Без указания параметров события.

2024-10-03 17:40 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-03 17:42 UTC, ShGKme commented on 03-components/30-removable-emails/EmailListItem.js
> +  emits: ['removeEmail:index'],
Аналогично с именем события

2024-10-03 17:43 UTC, ShGKme commented on 03-components/30-removable-emails/EmailListItem.js
> +      index: Number,
И здесь осталось лишнее свойство.

2024-10-03 17:43 UTC, ShGKme reviewed
Принято, но пара мелочей осталась

2024-10-03 17:46 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-03 18:57 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-03 18:58 UTC, ShGKme approved these changes

2024-10-03 19:00 UTC, merged